version: "3"
services:
 mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    ports:
    - 3306
    env_file:
    - .env
    restart: always
    networks:
    - boujdour
    volumes:
            - db_data:/var/lib/mysql  
 nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    ports:
    - 443:443
    restart: always
    networks:
    - boujdour
    depends_on:
            - wordpress
    volumes:
            - wp_data:/var/www/html/

 wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    ports:
    - 9000
    restart: always
    env_file:
    - .env
    networks:
    - boujdour
    depends_on:
            - mariadb
    volumes:
          - wp_data:/var/www/html/

 redis:
    build: ./requirements/bonus/redis
    image: redis
    container_name: redis
    ports:
    - 6379:6379
    restart: always
    depends_on:
           - wordpress
    networks:
    - boujdour

 portfolio :
    build: ./requirements/bonus/portfolio
    image: portfolio
    container_name: portfolio
    ports:
    - 3000:3000
    restart: always
    networks:
    - boujdour

 adminer :
    build: ./requirements/bonus/adminer
    image: adminer
    container_name: adminer
    ports :
    - 8888:8888
    restart: always
    networks:
    - boujdour

 cadvisor:
    build: ./requirements/bonus/cadvisor
    image: cadvisor
    container_name: cadvisor
    restart: always
    networks:
    - boujdour
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro 
    ports :
    - 8080:8080

volumes:
    wp_data:
        driver: local
        driver_opts:
            type: none
            device: "/home/ahmaidi/data/wordpress_data"
            o: bind
    db_data:
        driver: local
        driver_opts:
            type: none
            device: "/home/ahmaidi/data/database"
            o: bind
networks:
    boujdour:
        name: boujdour
        driver: bridge
